"""
train_runpod_indian_law.py — Phase 3b Indian Law, GPU-agnostic for RunPod
==========================================================================
Fine-tunes Mistral-7B-Instruct-v0.2 on Indian legal Q&A for JusticeAI alignment.

  Primary (~60%):  viber1/indian-law-dataset
                   Indian law Q&A covering IPC/BNS, CPC/BNSS, Constitution, BSA
                   Format: {question, answer}
                   NOTE: Pre-2024 vintage. Cites repealed IPC sections.

  Auxiliary (25%): Exploration-Lab/InLegalNLI
                   NLI pairs from Indian SC/HC judgments
                   Reformatted as legal reasoning Q&A
                   NOTE: Pre-2024 jurisprudence — still authoritative as precedent.

  BNS map (15%):   data/bns_bnss_bsa_mapping.jsonl  (locally generated)
                   IPC→BNS / CrPC→BNSS / IEA→BSA mappings
                   ~800 samples from 109 hand-curated seed mappings
                   Run scripts/build_bns_mapping_dataset.py to (re)build it.
                   Teaches model the post-July-2024 statute numbers it would
                   otherwise never see in the larger pre-2024 datasets.

Why r=32 (not r=16):
  Indian law is a specialized distribution far from Mistral's pretraining.
  The larger adapter rank captures more domain-specific legal reasoning
  without increasing inference cost (adapters are merged at deployment).

JusticeAI alignment:
  This adapter teaches BNS/BNSS/BSA section references (post-July 2024 codes),
  Indian SC judgment reasoning style, and bail-specific legal analysis —
  directly feeding into JusticeAI Phase 1 (bail decisions).

GPU tiers (seq_len=2048, r=32 adapter is slightly larger than r=16):

    VRAM >= 70GB  (A100 80GB, H100 80GB):
        bf16 LoRA, batch=8,  no grad ckpt, flash-attn2  → ~25 min

    VRAM >= 40GB  (A40/L40S/A6000 48GB):
        bf16 LoRA, batch=4,  no grad ckpt, flash-attn2  → ~40 min

    VRAM >= 22GB  (RTX 4090 / A5000 24GB):
        4-bit QLoRA, batch=4, grad ckpt on, flash-attn2 → ~70 min

    VRAM < 22GB   (T4 16GB, etc.):
        4-bit QLoRA, batch=2, grad ckpt on, no flash-attn → ~140 min

Setup on RunPod:
    cd /workspace && git clone <repo> jobs-prjcts && cd jobs-prjcts/03-llm-finetuning
    pip install -r requirements_runpod.txt
    huggingface-cli login
    python scripts/train_runpod_indian_law.py
"""

import json
import os
import re
import time

import torch
from datasets import load_dataset, concatenate_datasets
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from trl import SFTConfig, SFTTrainer


# ─────────────────────────────────────────────
# Static config
# ─────────────────────────────────────────────

BASE_MODEL      = "mistralai/Mistral-7B-Instruct-v0.2"
PRIMARY_DATASET = "viber1/indian-law-dataset"
AUX_DATASET     = "Exploration-Lab/InLegalNLI"
BNS_DATASET_PATH = "data/bns_bnss_bsa_mapping.jsonl"   # local file generated by build_bns_mapping_dataset.py
OUTPUT_DIR      = "/workspace/outputs/phase3b-indian-law"

NUM_EPOCHS      = 4
LEARNING_RATE   = 1.0e-4
MAX_SEQ_LENGTH  = 2048
LOGGING_STEPS   = 10
SAVE_STEPS      = 100

LORA_R          = 32           # higher rank — larger domain gap from Mistral's training
LORA_ALPHA      = 64
LORA_DROPOUT    = 0.05
TARGET_MODULES  = ["q_proj", "k_proj", "v_proj", "o_proj",
                   "gate_proj", "up_proj", "down_proj"]

TEST_SIZE       = 0.10
AUX_SAMPLES     = 3000         # InLegalNLI samples to mix in
AUX_WEIGHT      = 0.25         # 25% of mixed dataset from InLegalNLI
BNS_WEIGHT      = 0.15         # 15% of mixed dataset from BNS/BNSS/BSA mapping
# ^ The BNS mapping dataset (~800 samples) is small but critical: it teaches the
#   model that IPC §302 → BNS §103, etc. Without it, the model would confidently
#   cite repealed colonial-era sections for post-July-2024 cases (a hard failure
#   mode for JusticeAI). 15% weight = high signal-to-sample ratio.

INDIAN_LAW_SYSTEM = (
    "You are an expert in Indian law with deep knowledge of the Bharatiya Nyaya Sanhita "
    "(BNS, 2023), Bharatiya Nagarik Suraksha Sanhita (BNSS, 2023), Bharatiya Sakshya "
    "Adhiniyam (BSA, 2023), the Constitution of India, and Indian Supreme Court and High "
    "Court jurisprudence. When answering legal questions, cite the correct current statutes "
    "(BNS/BNSS/BSA for post-July 2024 matters, IPC/CrPC/IEA for historical cases), "
    "reference relevant Supreme Court precedents where applicable, and provide accurate, "
    "precise legal analysis. Clearly distinguish between the old codes (IPC/CrPC) and the "
    "new codes (BNS/BNSS/BSA) when the distinction is legally material."
)

# Rubric used in the LLM judge prompt — also embedded in evaluate.py
INDIAN_LAW_JUDGE_RUBRIC = """Rating criteria for Indian law responses:
1 — Wrong statute cited, incorrect legal principle, or factually wrong
2 — Correct general area but wrong section numbers or significant procedural errors
3 — Correct answer but missing key nuance (e.g. old vs new code distinction)
4 — Correct, proper citations, minor omissions in nuance or case law
5 — Accurate, correct BNS/BNSS/BSA vs IPC/CrPC distinction, relevant SC precedents cited"""


# ─────────────────────────────────────────────
# GPU auto-detect
# ─────────────────────────────────────────────

def detect_gpu_tier() -> dict:
    if not torch.cuda.is_available():
        raise RuntimeError("No CUDA GPU detected.")

    props      = torch.cuda.get_device_properties(0)
    name       = props.name
    vram_gb    = props.total_memory / 1e9
    capability = props.major + props.minor / 10
    bf16_ok    = capability >= 8.0
    flash_ok   = capability >= 8.0 and not os.environ.get("NO_FLASH")
    force_4bit = bool(os.environ.get("USE_4BIT"))

    print(f"GPU: {name}  ({vram_gb:.1f} GB, sm_{props.major}{props.minor})")
    print(f"bf16 supported: {bf16_ok} | flash-attn2 eligible: {flash_ok}")

    if vram_gb >= 70 and not force_4bit:
        tier = dict(label="A100/H100 80GB tier", use_4bit=False,
                    batch_size=8, grad_accum=2, grad_ckpt=False)
    elif vram_gb >= 40 and not force_4bit:
        tier = dict(label="A40/L40S/A6000 48GB tier", use_4bit=False,
                    batch_size=4, grad_accum=4, grad_ckpt=False)
    elif vram_gb >= 22:
        tier = dict(label="RTX 4090 / A5000 24GB tier", use_4bit=True,
                    batch_size=4, grad_accum=4, grad_ckpt=True)
    else:
        tier = dict(label="T4 / small-VRAM tier", use_4bit=True,
                    batch_size=2, grad_accum=8, grad_ckpt=True)

    if os.environ.get("BATCH_SIZE"):
        tier["batch_size"] = int(os.environ["BATCH_SIZE"])

    tier.update(bf16=bf16_ok, fp16=not bf16_ok,
                flash=flash_ok, vram_gb=vram_gb, gpu_name=name)

    print(f"\nSelected tier: {tier['label']}")
    print(f"  use_4bit         = {tier['use_4bit']}")
    print(f"  batch_size       = {tier['batch_size']}  "
          f"(grad_accum={tier['grad_accum']}, "
          f"effective={int(tier['batch_size'])*int(tier['grad_accum'])})")
    print(f"  grad_checkpoint  = {tier['grad_ckpt']}")
    print(f"  precision        = {'bf16' if tier['bf16'] else 'fp16'}")
    print(f"  flash_attention2 = {tier['flash']}\n")
    return tier


# ─────────────────────────────────────────────
# Model loading
# ─────────────────────────────────────────────

def load_model_and_tokenizer(tier: dict):
    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
        tokenizer.pad_token_id = tokenizer.eos_token_id
    tokenizer.padding_side = "right"

    load_kwargs: dict = {"device_map": {"": 0}, "trust_remote_code": True}
    if tier["flash"]:
        load_kwargs["attn_implementation"] = "flash_attention_2"

    if tier["use_4bit"]:
        print(f"Loading {BASE_MODEL} in 4-bit NF4...")
        bnb = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.bfloat16 if tier["bf16"] else torch.float16,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_use_double_quant=True,
        )
        model = AutoModelForCausalLM.from_pretrained(
            BASE_MODEL, quantization_config=bnb, **load_kwargs
        )
        model = prepare_model_for_kbit_training(
            model, use_gradient_checkpointing=tier["grad_ckpt"]
        )
    else:
        print(f"Loading {BASE_MODEL} in bf16...")
        model = AutoModelForCausalLM.from_pretrained(
            BASE_MODEL,
            torch_dtype=torch.bfloat16 if tier["bf16"] else torch.float16,
            **load_kwargs,
        )

    print(f"Model loaded. GPU memory: {torch.cuda.memory_allocated() / 1e9:.2f} GB")
    return model, tokenizer


def inject_lora(model):
    lora_config = LoraConfig(
        r=LORA_R, lora_alpha=LORA_ALPHA, lora_dropout=LORA_DROPOUT,
        bias="none", task_type="CAUSAL_LM", target_modules=TARGET_MODULES,
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()
    return model


# ─────────────────────────────────────────────
# Dataset
# ─────────────────────────────────────────────

def format_indian_law_sample(sample: dict, tokenizer) -> str:
    """
    viber1/indian-law-dataset fields: {question, answer}

    The system prompt explicitly references BNS/BNSS/BSA so the model learns
    to prefer new statute citations for post-2024 questions while correctly
    referencing IPC/CrPC for historical/precedent context.
    """
    question = sample.get("question", "").strip()
    answer   = sample.get("answer", "").strip()

    messages = [
        {"role": "system",    "content": INDIAN_LAW_SYSTEM},
        {"role": "user",      "content": question},
        {"role": "assistant", "content": answer},
    ]
    return tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=False
    )


def format_bns_mapping_sample(sample: dict, tokenizer) -> str:
    """
    BNS/BNSS/BSA mapping samples are simple {question, answer} pairs generated by
    build_bns_mapping_dataset.py. Uses the same system prompt as the primary dataset
    to keep formatting consistent — the model learns these are authoritative Indian
    law answers with correct post-2024 statute references.
    """
    question = sample.get("question", "").strip()
    answer   = sample.get("answer", "").strip()

    messages = [
        {"role": "system",    "content": INDIAN_LAW_SYSTEM},
        {"role": "user",      "content": question},
        {"role": "assistant", "content": answer},
    ]
    return tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=False
    )


def format_inlegalnli_sample(sample: dict, tokenizer) -> str:
    """
    Exploration-Lab/InLegalNLI fields:
        premise    : Indian SC/HC judgment excerpt
        hypothesis : a legal claim about the judgment
        label      : 0=entailment, 1=neutral, 2=contradiction

    Reformatted as a legal reasoning task:
    "Does the following court judgment support this legal claim? Explain why."

    This teaches the model to reason about Indian court language and precedent,
    which directly supports JusticeAI's citation-grounded bail analysis.
    """
    premise    = sample.get("premise", "").strip()
    hypothesis = sample.get("hypothesis", "").strip()
    label_id   = sample.get("label", 1)

    label_map = {0: "Yes, the judgment supports this claim",
                 1: "The judgment neither clearly supports nor contradicts this claim",
                 2: "No, the judgment contradicts this claim"}
    label_text = label_map.get(label_id, label_map[1])

    # Truncate long judgment excerpts to fit within seq budget
    if len(premise) > 1200:
        premise = premise[:1200] + "..."

    user_content = (
        f"Court Judgment Excerpt:\n{premise}\n\n"
        f"Legal Claim: {hypothesis}\n\n"
        f"Does the judgment support this legal claim? Explain your reasoning."
    )
    # Generate a short but informative answer from the label
    answer = (
        f"{label_text}.\n\n"
        f"The judgment excerpt {'explicitly establishes' if label_id == 0 else 'does not establish' if label_id == 2 else 'does not directly address'} "
        f"the proposition that {hypothesis.lower().rstrip('.')}."
    )

    messages = [
        {"role": "system",    "content": INDIAN_LAW_SYSTEM},
        {"role": "user",      "content": user_content},
        {"role": "assistant", "content": answer},
    ]
    return tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=False
    )


def _load_bns_mapping_dataset(tokenizer):
    """
    Load the locally-generated BNS/BNSS/BSA mapping dataset.
    Returns None if the file is missing (allows training to proceed without it,
    but logs a strong warning — JusticeAI critically depends on this dataset).
    """
    # Resolve path relative to script's parent (the project root)
    script_dir   = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    bns_path     = os.path.join(project_root, BNS_DATASET_PATH)

    if not os.path.exists(bns_path):
        print(f"\n{'!'*70}")
        print(f"WARNING: BNS mapping dataset not found at {bns_path}")
        print(f"Run: python scripts/build_bns_mapping_dataset.py")
        print(f"Without this, model will cite REPEALED IPC/CrPC sections in production.")
        print(f"{'!'*70}\n")
        return None

    print(f"Loading BNS mapping dataset: {bns_path}")
    bns_raw = load_dataset("json", data_files=bns_path, split="train")
    bns_formatted = bns_raw.map(
        lambda s: {"text": format_bns_mapping_sample(s, tokenizer)},
        remove_columns=bns_raw.column_names,
    )
    print(f"BNS mapping — {len(bns_formatted)} samples loaded "
          f"(post-July-2024 statute references)")
    return bns_formatted


def load_data(tokenizer):
    """
    Build a 3-way training mix:
        Primary    (~60%):  viber1/indian-law-dataset    — broad Indian law Q&A
        Auxiliary  (~25%):  Exploration-Lab/InLegalNLI   — SC/HC reasoning
        BNS map    (~15%):  local bns_bnss_bsa_mapping.jsonl — post-2024 statute updates

    The BNS mapping is small (~800 samples) but high-signal: it directly corrects the
    pre-2024 framing baked into the larger datasets. Training sees it across multiple
    epochs (NUM_EPOCHS=4) so the model genuinely learns BNS section numbers.
    """
    print(f"Loading primary dataset: {PRIMARY_DATASET}...")
    raw   = load_dataset(PRIMARY_DATASET, split="train")
    split = raw.train_test_split(test_size=TEST_SIZE, seed=42)
    train_raw, test_raw = split["train"], split["test"]
    print(f"Primary — Train: {len(train_raw)} | Test: {len(test_raw)}")

    train_primary = train_raw.map(
        lambda s: {"text": format_indian_law_sample(s, tokenizer)},
        remove_columns=train_raw.column_names,
    )

    components: list = [("primary", train_primary, 1.0 - AUX_WEIGHT - BNS_WEIGHT)]

    # Auxiliary: InLegalNLI
    print(f"Loading auxiliary dataset: {AUX_DATASET} ({AUX_SAMPLES} samples)...")
    try:
        aux_raw = load_dataset(AUX_DATASET, split="train")
        aux_raw = aux_raw.select(range(min(AUX_SAMPLES, len(aux_raw))))
        train_aux = aux_raw.map(
            lambda s: {"text": format_inlegalnli_sample(s, tokenizer)},
            remove_columns=aux_raw.column_names,
        )
        print(f"Auxiliary (InLegalNLI) — {len(train_aux)} samples loaded")
        components.append(("aux", train_aux, AUX_WEIGHT))
    except Exception as e:
        print(f"WARNING: Could not load auxiliary dataset ({e}). Skipping.")

    # BNS/BNSS/BSA mapping (local file)
    bns_dataset = _load_bns_mapping_dataset(tokenizer)
    if bns_dataset is not None:
        components.append(("bns_map", bns_dataset, BNS_WEIGHT))

    # Re-normalise weights if any component was skipped
    total_weight = sum(w for _, _, w in components)
    components = [(name, ds, w / total_weight) for name, ds, w in components]

    # Pick the anchor: the smallest dataset relative to its weight defines the
    # achievable mix size. Each component is then sampled to match its weight.
    achievable_sizes = [len(ds) / w for _, ds, w in components if w > 0]
    anchor_size      = min(achievable_sizes)

    chunks = []
    summary_parts = []
    for name, ds, w in components:
        n = min(int(anchor_size * w), len(ds))
        # If the BNS mapping is small, oversample by repeating (small but critical)
        if name == "bns_map" and n < len(ds):
            n = len(ds)   # use all of it — never drop BNS samples
        chunks.append(ds.select(range(min(n, len(ds)))))
        summary_parts.append(f"{n} {name}")

    mixed = concatenate_datasets(chunks).shuffle(seed=42)
    print(f"\nMixed dataset: {len(mixed)} samples ({' + '.join(summary_parts)})")
    weight_summary = ", ".join(f"{name}={w:.0%}" for name, _, w in components)
    print(f"Target weights: {weight_summary}\n")

    return mixed, test_raw


# ─────────────────────────────────────────────
# Training
# ─────────────────────────────────────────────

def train(model, tokenizer, train_dataset, tier: dict):
    optim = "adamw_torch_fused" if not tier["use_4bit"] else "paged_adamw_32bit"

    training_args = SFTConfig(
        output_dir=OUTPUT_DIR,
        num_train_epochs=NUM_EPOCHS,
        per_device_train_batch_size=tier["batch_size"],
        gradient_accumulation_steps=tier["grad_accum"],
        learning_rate=LEARNING_RATE,
        lr_scheduler_type="cosine",
        warmup_ratio=0.05,          # longer warmup for r=32 adapter
        bf16=tier["bf16"],
        fp16=tier["fp16"],
        logging_steps=LOGGING_STEPS,
        save_steps=SAVE_STEPS,
        save_total_limit=3,         # keep 3 checkpoints — useful for epoch 3 vs 4 comparison
        report_to="none",
        optim=optim,
        gradient_checkpointing=tier["grad_ckpt"],
        group_by_length=True,
        max_seq_length=MAX_SEQ_LENGTH,
        dataset_text_field="text",
        packing=False,
        dataloader_num_workers=4,
        dataloader_pin_memory=True,
        tf32=tier["bf16"],
    )

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=train_dataset,
        args=training_args,
    )

    eff_batch       = tier["batch_size"] * tier["grad_accum"]
    steps_per_epoch = len(train_dataset) // eff_batch
    print(f"\nTraining: {len(train_dataset)} samples × {NUM_EPOCHS} epochs")
    print(f"Effective batch: {eff_batch} | Steps/epoch: ~{steps_per_epoch} | "
          f"Total: ~{steps_per_epoch * NUM_EPOCHS}")
    print(f"LoRA rank: r={LORA_R} (higher than prior phases — larger domain gap)\n")

    t0 = time.time()
    trainer.train()
    print(f"\nTraining wall time: {(time.time() - t0) / 60:.1f} min")

    adapter_path = os.path.join(OUTPUT_DIR, "final-adapter")
    trainer.model.save_pretrained(adapter_path)
    tokenizer.save_pretrained(adapter_path)
    print(f"Adapter saved: {adapter_path}")
    return trainer, adapter_path


# ─────────────────────────────────────────────
# Post-training eval (Indian law LLM-as-judge)
# ─────────────────────────────────────────────

def evaluate_indian_law(model, tokenizer, test_raw, adapter_path: str, tier: dict,
                        groq_api_key: str | None = None):
    """
    LLM-as-judge with an Indian law-specific rubric.
    The judge checks: correct statute (BNS vs IPC), section accuracy, SC precedents.
    """
    try:
        from groq import Groq
    except ImportError:
        print("Skipping eval: 'groq' not installed. pip install groq")
        return {}

    api_key = groq_api_key or os.environ.get("GROQ_API_KEY")
    if not api_key:
        print("Skipping eval: GROQ_API_KEY not set.")
        return {}

    from tqdm import tqdm

    groq_client = Groq(api_key=api_key)
    judge_model = "llama-3.3-70b-versatile"
    max_eval    = min(100, len(test_raw))
    samples     = test_raw.select(range(max_eval))

    model.eval()
    scores  = []
    records = []

    for sample in tqdm(samples, desc="Indian law LLM-judge eval"):
        question     = sample.get("question", "").strip()
        ground_truth = sample.get("answer", "").strip()

        # Generate response
        messages  = [{"role": "system", "content": INDIAN_LAW_SYSTEM},
                     {"role": "user",   "content": question}]
        formatted = tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        inputs    = tokenizer(formatted, return_tensors="pt").to(model.device)
        input_len = inputs["input_ids"].shape[1]

        with torch.no_grad():
            out = model.generate(
                **inputs, max_new_tokens=350, temperature=0.1,
                top_p=0.9, do_sample=True, pad_token_id=tokenizer.eos_token_id,
            )
        response = tokenizer.decode(out[0][input_len:], skip_special_tokens=True).strip()

        judge_prompt = f"""You are an expert evaluator of Indian law responses. Rate this AI response on a 1-5 scale.

Question: {question[:400]}

Reference answer: {ground_truth[:500]}

AI response: {response[:500]}

{INDIAN_LAW_JUDGE_RUBRIC}

Respond with ONLY a single digit (1-5). No explanation."""

        try:
            completion = groq_client.chat.completions.create(
                model=judge_model,
                messages=[{"role": "user", "content": judge_prompt}],
                max_tokens=5, temperature=0,
            )
            score_text = completion.choices[0].message.content or ""
            m = re.search(r'[1-5]', score_text.strip())
            score = int(m.group()) if m else 3
        except Exception as e:
            print(f"Groq error: {e}")
            score = 3

        scores.append(score)
        records.append({"question": question[:80], "score": score,
                        "response": response[:150]})

    avg_score  = sum(scores) / len(scores) if scores else 0.0
    score_dist = {str(i): scores.count(i) for i in range(1, 6)}

    results = {
        "phase":      "phase3b_indian_law",
        "gpu":        tier["gpu_name"],
        "vram_gb":    round(tier["vram_gb"], 1),
        "tier":       tier["label"],
        "model":      BASE_MODEL,
        "adapter":    adapter_path,
        "dataset":    PRIMARY_DATASET,
        "judge":      judge_model,
        "lora_r":     LORA_R,
        "num_eval":   len(scores),
        "avg_score":  round(avg_score, 3),
        "score_dist": score_dist,
    }

    print(f"\n{'='*50}")
    print(f"INDIAN LAW LLM-JUDGE ({judge_model})")
    print(f"Average score: {avg_score:.2f}/5.0")
    print(f"Distribution:  {score_dist}")
    print(f"Baseline (Mistral base on Indian law): ~2.5/5.0")
    print(f"Target: ≥3.5/5.0 (+1.0 pts improvement)")
    print(f"{'='*50}")

    out_path = os.path.join(OUTPUT_DIR, "eval_results.json")
    with open(out_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"Results saved: {out_path}")
    return results


# ─────────────────────────────────────────────
# Entrypoint
# ─────────────────────────────────────────────

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--skip-eval", action="store_true",
                        help="Train only, skip LLM-judge evaluation")
    parser.add_argument("--groq-key", default=None,
                        help="Groq API key (fallback: GROQ_API_KEY env var)")
    parser.add_argument("--push-hub", default=None,
                        help="HF repo to push adapter (e.g. anksriv/mistral-7b-indian-law-qlora)")
    args = parser.parse_args()

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    print(f"PyTorch: {torch.__version__}  |  CUDA: {torch.version.cuda}\n")
    print("Phase 3b: Indian Law Fine-Tuning (JusticeAI Adapter)")
    print(f"Primary dataset:   {PRIMARY_DATASET}  (~60% mix)")
    print(f"Auxiliary dataset: {AUX_DATASET}  (~25% mix)")
    print(f"BNS mapping data:  {BNS_DATASET_PATH}  (~15% mix — post-2024 statute updates)")
    print(f"LoRA rank: r={LORA_R} (increased from r=16 in prior phases)\n")

    tier = detect_gpu_tier()
    model, tokenizer        = load_model_and_tokenizer(tier)
    model                   = inject_lora(model)
    train_dataset, test_raw = load_data(tokenizer)
    trainer, adapter_path   = train(model, tokenizer, train_dataset, tier)

    if not args.skip_eval:
        evaluate_indian_law(trainer.model, tokenizer, test_raw, adapter_path, tier,
                            groq_api_key=args.groq_key)

    if args.push_hub:
        print(f"\nPushing adapter to {args.push_hub}...")
        trainer.model.push_to_hub(args.push_hub)
        tokenizer.push_to_hub(args.push_hub)
        print(f"Pushed: https://huggingface.co/{args.push_hub}")
        print("Note: Tag this as 'JusticeAI Phase 1 adapter' in the HF model card.")


if __name__ == "__main__":
    main()
